import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :subzero_swarm_dashboard, SubzeroSwarmDashboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force SSL by default. A dashboard bound only to a private Tailscale address
# can explicitly compile with DASHBOARD_FORCE_SSL=false and serve plain HTTP
# without redirecting clients to a TLS listener that does not exist.
if System.get_env("DASHBOARD_FORCE_SSL", "true") != "false" do
  config :subzero_swarm_dashboard, SubzeroSwarmDashboardWeb.Endpoint,
    force_ssl: [
      rewrite_on: [:x_forwarded_proto],
      exclude: [
        # paths: ["/health"],
        hosts: ["localhost", "127.0.0.1"]
      ]
    ]
end

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
